In [2]:
import os
import pandas as pd

path = "D:\keti_bigdata_platform\keti_bigdata\사울31바7708"
# path data 매개변수로 입력 하게 변경

file_list = os.listdir(path)
file_list_csv = [file for file in file_list if file.endswith(".csv")]
print("원본 file 갯수:", len(file_list_csv))

new_file_list_csv = []

for file in file_list_csv:
    print(file)
    file_size = os.path.getsize(file)
    # print(file_size)
    if file_size != 0:
        new_file_list_csv.append(file)

print("new file 갯수:", len(file_list_csv))
# new file : file size가 0이 아닌 파일


# new_file_name = new_file_list_csv[0].split('_')[1].split('-')[0]
# print(new_file_name)

df_list = []

for file_list in new_file_list_csv:
    df_name = file_list.split('_')[1].split('-')[0]
    # print(df_name)
    df_list.append(df_name)

print("df_name 갯수 : ", len(df_list))
# for df_name in df_list:
#    print(df_name)

원본 file 갯수: 83
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210903010700000-20210903020700000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210903020700000-20210903030700000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210903030700000-20210903040700000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210903040700000-20210903050700000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210903050700000-20210903060700000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210903060700000-20210903070700000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210903070700000-20210903080700000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210903080700000-20210903090700000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210903090700000-20210903100700000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210903100700000-20210903110700000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210904221100000-20210904231100000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210904231100000-20210905001100000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210905001100000-20210905011100000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210905011100000-20210905021100000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210905021100000-20210905031100000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210905031100000-20210905041100000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210907124800000-20210907134800000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210907134800000-20210907144800000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210907144800000-20210907154800000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210907154800000-20210907164800000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210907164800000-20210907174800000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210907174800000-20210907184800000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210907184800000-20210907194800000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210909065800000-20210909075800000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210909075800000-20210909085800000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210909085800000-20210909095800000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210909095800000-20210909105800000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210909105800000-20210909115800000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210909115800000-20210909125800000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210909125800000-20210909135800000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210912073900000-20210912083900000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210912083900000-20210912093900000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210912093900000-20210912103900000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210912103900000-20210912113900000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210912113900000-20210912123900000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210912123900000-20210912133900000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210912133900000-20210912143900000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210912143900000-20210912153900000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210912153900000-20210912163900000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210912163900000-20210912173900000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210919084600000-20210919094600000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210919094600000-20210919104600000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210919104600000-20210919114600000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210919114600000-20210919124600000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210919124600000-20210919134600000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210919134600000-20210919144600000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210919144600000-20210919154600000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210919154600000-20210919164600000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210919164600000-20210919174600000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210919174600000-20210919184600000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210921190300000-20210921200300000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210921200300000-20210921210300000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210921210300000-20210921220300000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210921220300000-20210921230300000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210921230300000-20210922000300000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210925044900000-20210925054900000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210925054900000-20210925064900000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210925064900000-20210925074900000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210925074900000-20210925084900000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210925084900000-20210925094900000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210926091400000-20210926101400000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210926101400000-20210926111400000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210926111400000-20210926121400000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210926121400000-20210926131400000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210926131400000-20210926141400000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210926141400000-20210926151400000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210926151400000-20210926161400000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210926161400000-20210926171400000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210926171400000-20210926181400000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210926181400000-20210926191400000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210926191400000-20210926201400000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210930024600000-20210930034600000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210930034600000-20210930044600000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210930044600000-20210930054600000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210930054600000-20210930064600000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210930064600000-20210930074600000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20210930074600000-20210930084600000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20211002075700000-20211002085700000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20211002085700000-20211002095700000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20211002095700000-20211002105700000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20211002105700000-20211002115700000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20211002115700000-20211002125700000.csv
fdc1f303c745ad32e1faa6279609e338a03efa94082d6def5e1893348c24cc75_20211002125700000-20211002135700000.csv
new file 갯수: 83
df_name 갯수 :  83

In [3]:
for file_csv in new_file_list_csv:
    df_temp = pd.read_csv(file_csv, sep='\t')
    df_temp.info()
    df_temp.shape
    df_temp.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6842 entries, 0 to 6841
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6842 non-null   object
dtypes: object(1)
memory usage: 26.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6842 entries, 0 to 6841
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6842 non-null   object
dtypes: object(1)
memory usage: 26.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6962 entries, 0 to 6961
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6962 non-null   object
dtypes: object(1)
memory usage: 27.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6842 entries, 0 to 6841
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6842 non-null   object
dtypes: object(1)
memory usage: 26.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6842 entries, 0 to 6841
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6842 non-null   object
dtypes: object(1)
memory usage: 26.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6962 entries, 0 to 6961
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6962 non-null   object
dtypes: object(1)
memory usage: 27.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6842 entries, 0 to 6841
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6842 non-null   object
dtypes: object(1)
memory usage: 26.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6842 entries, 0 to 6841
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6842 non-null   object
dtypes: object(1)
memory usage: 26.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5882 entries, 0 to 5881
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  5882 non-null   object
dtypes: object(1)
memory usage: 23.0+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 722 entries, 0 to 721
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  722 non-null    object
dtypes: object(1)
memory usage: 2.9+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3482 entries, 0 to 3481
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  3482 non-null   object
dtypes: object(1)
memory usage: 13.7+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6842 entries, 0 to 6841
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6842 non-null   object
dtypes: object(1)
memory usage: 26.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6842 entries, 0 to 6841
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6842 non-null   object
dtypes: object(1)
memory usage: 26.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6722 entries, 0 to 6721
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6722 non-null   object
dtypes: object(1)
memory usage: 26.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6842 entries, 0 to 6841
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6842 non-null   object
dtypes: object(1)
memory usage: 26.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6842 entries, 0 to 6841
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6842 non-null   object
dtypes: object(1)
memory usage: 26.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122 entries, 0 to 121
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  122 non-null    object
dtypes: object(1)
memory usage: 552.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6842 entries, 0 to 6841
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6842 non-null   object
dtypes: object(1)
memory usage: 26.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6842 entries, 0 to 6841
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6842 non-null   object
dtypes: object(1)
memory usage: 26.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6362 entries, 0 to 6361
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6362 non-null   object
dtypes: object(1)
memory usage: 24.9+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6842 entries, 0 to 6841
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6842 non-null   object
dtypes: object(1)
memory usage: 26.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3962 entries, 0 to 3961
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  3962 non-null   object
dtypes: object(1)
memory usage: 15.5+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6362 entries, 0 to 6361
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6362 non-null   object
dtypes: object(1)
memory usage: 24.9+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6842 entries, 0 to 6841
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6842 non-null   object
dtypes: object(1)
memory usage: 26.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6842 entries, 0 to 6841
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6842 non-null   object
dtypes: object(1)
memory usage: 26.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3962 entries, 0 to 3961
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  3962 non-null   object
dtypes: object(1)
memory usage: 15.5+ KB

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6842 entries, 0 to 6841
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6842 non-null   object
dtypes: object(1)
memory usage: 26.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6842 entries, 0 to 6841
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6842 non-null   object
dtypes: object(1)
memory usage: 26.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3962 entries, 0 to 3961
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  3962 non-null   object
dtypes: object(1)
memory usage: 15.5+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6842 entries, 0 to 6841
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6842 non-null   object
dtypes: object(1)
memory usage: 26.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6962 entries, 0 to 6961
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6962 non-null   object
dtypes: object(1)
memory usage: 27.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6842 entries, 0 to 6841
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6842 non-null   object
dtypes: object(1)
memory usage: 26.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6842 entries, 0 to 6841
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6842 non-null   object
dtypes: object(1)
memory usage: 26.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6842 entries, 0 to 6841
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6842 non-null   object
dtypes: object(1)
memory usage: 26.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6842 entries, 0 to 6841
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6842 non-null   object
dtypes: object(1)
memory usage: 26.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6842 entries, 0 to 6841
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6842 non-null   object
dtypes: object(1)
memory usage: 26.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6842 entries, 0 to 6841
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6842 non-null   object
dtypes: object(1)
memory usage: 26.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6842 entries, 0 to 6841
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6842 non-null   object
dtypes: object(1)
memory usage: 26.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6842 entries, 0 to 6841
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6842 non-null   object
dtypes: object(1)
memory usage: 26.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6842 entries, 0 to 6841
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6842 non-null   object
dtypes: object(1)
memory usage: 26.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6842 entries, 0 to 6841
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6842 non-null   object
dtypes: object(1)
memory usage: 26.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 722 entries, 0 to 721
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  722 non-null    object
dtypes: object(1)
memory usage: 2.9+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6842 entries, 0 to 6841
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6842 non-null   object
dtypes: object(1)
memory usage: 26.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5882 entries, 0 to 5881
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  5882 non-null   object
dtypes: object(1)
memory usage: 23.0+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6842 entries, 0 to 6841
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6842 non-null   object
dtypes: object(1)
memory usage: 26.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6842 entries, 0 to 6841
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6842 non-null   object
dtypes: object(1)
memory usage: 26.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1082 entries, 0 to 1081
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  1082 non-null   object
dtypes: object(1)
memory usage: 4.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6962 entries, 0 to 6961
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6962 non-null   object
dtypes: object(1)
memory usage: 27.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6842 entries, 0 to 6841
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6842 non-null   object
dtypes: object(1)
memory usage: 26.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5042 entries, 0 to 5041
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  5042 non-null   object
dtypes: object(1)
memory usage: 19.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 722 entries, 0 to 721
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  722 non-null    object
dtypes: object(1)
memory usage: 2.9+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6842 entries, 0 to 6841
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6842 non-null   object
dtypes: object(1)
memory usage: 26.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1082 entries, 0 to 1081
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  1082 non-null   object
dtypes: object(1)
memory usage: 4.3+ KB

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6842 entries, 0 to 6841
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6842 non-null   object
dtypes: object(1)
memory usage: 26.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6842 entries, 0 to 6841
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6842 non-null   object
dtypes: object(1)
memory usage: 26.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6842 entries, 0 to 6841
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6842 non-null   object
dtypes: object(1)
memory usage: 26.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6842 entries, 0 to 6841
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6842 non-null   object
dtypes: object(1)
memory usage: 26.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1082 entries, 0 to 1081
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  1082 non-null   object
dtypes: object(1)
memory usage: 4.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6362 entries, 0 to 6361
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6362 non-null   object
dtypes: object(1)
memory usage: 24.9+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6842 entries, 0 to 6841
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6842 non-null   object
dtypes: object(1)
memory usage: 26.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6842 entries, 0 to 6841
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6842 non-null   object
dtypes: object(1)
memory usage: 26.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6842 entries, 0 to 6841
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6842 non-null   object
dtypes: object(1)
memory usage: 26.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6842 entries, 0 to 6841
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6842 non-null   object
dtypes: object(1)
memory usage: 26.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1082 entries, 0 to 1081
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  1082 non-null   object
dtypes: object(1)
memory usage: 4.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6842 entries, 0 to 6841
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6842 non-null   object
dtypes: object(1)
memory usage: 26.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6842 entries, 0 to 6841
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6842 non-null   object
dtypes: object(1)
memory usage: 26.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122 entries, 0 to 121
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  122 non-null    object
dtypes: object(1)
memory usage: 552.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6842 entries, 0 to 6841
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6842 non-null   object
dtypes: object(1)
memory usage: 26.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3482 entries, 0 to 3481
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  3482 non-null   object
dtypes: object(1)
memory usage: 13.7+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6362 entries, 0 to 6361
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6362 non-null   object
dtypes: object(1)
memory usage: 24.9+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6962 entries, 0 to 6961
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6962 non-null   object
dtypes: object(1)
memory usage: 27.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6842 entries, 0 to 6841
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6842 non-null   object
dtypes: object(1)
memory usage: 26.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 242 entries, 0 to 241
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  242 non-null    object
dtypes: object(1)
memory usage: 1.0+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6842 entries, 0 to 6841
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6842 non-null   object
dtypes: object(1)
memory usage: 26.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5882 entries, 0 to 5881
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  5882 non-null   object
dtypes: object(1)
memory usage: 23.0+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6842 entries, 0 to 6841
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6842 non-null   object
dtypes: object(1)
memory usage: 26.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1082 entries, 0 to 1081
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  1082 non-null   object
dtypes: object(1)
memory usage: 4.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1082 entries, 0 to 1081
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  1082 non-null   object
dtypes: object(1)
memory usage: 4.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1082 entries, 0 to 1081
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  1082 non-null   object
dtypes: object(1)
memory usage: 4.3+ KB

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6962 entries, 0 to 6961
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6962 non-null   object
dtypes: object(1)
memory usage: 27.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6842 entries, 0 to 6841
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6842 non-null   object
dtypes: object(1)
memory usage: 26.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6842 entries, 0 to 6841
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6842 non-null   object
dtypes: object(1)
memory usage: 26.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6842 entries, 0 to 6841
Data columns (total 1 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   version,Car Type,Car Year,Car ID  6842 non-null   object
dtypes: object(1)
memory usage: 26.8+ KB